import type { CommentType } from "./types/postType";

export const sampleComments: CommentType[] = [
    {
        name: "Sarah Johnson",
        comment: "This is absolutely incredible! The cinematography is stunning and the storytelling keeps you engaged from start to finish. Can't wait to see more content like this! 🎬✨",
        createdAt: new Date(2024, 9, 1).toISOString(),
        avatar: "from-blue-400 to-cyan-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    },
    {
        name: "Mike Chen",
        comment: "Wow, this totally changed my perspective on the topic. The production quality is top-notch and the research is clearly thorough. Subscribed! 🔥",
        createdAt: new Date(2024, 9, 15).toISOString(),
        avatar: "from-green-400 to-emerald-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    },
    {
        name: "Emma Rodriguez",
        comment: "I've been following your work for a while now, and this might be your best piece yet. The attention to detail is remarkable!",
        createdAt: new Date(2024, 9, 20).toISOString(),
        avatar: "from-pink-400 to-rose-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    },
    {
        name: "David Park",
        comment: "As someone who works in this field, I really appreciate how accurately you presented everything. Great job!",
        createdAt: new Date(2024, 9, 25).toISOString(),
        avatar: "from-orange-400 to-amber-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    },
    {
        name: "Lisa Anderson",
        comment: "This deserves way more views! Sharing this with all my friends. Everyone needs to see this masterpiece! 🌟",
        createdAt: new Date(2024, 9, 28).toISOString(),
        avatar: "from-purple-400 to-violet-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    },
    {
        name: "James Wilson",
        comment: "The editing is so smooth and professional. What software do you use? Would love to learn more about your process!",
        createdAt: new Date(2024, 10, 1).toISOString(),
        avatar: "from-indigo-400 to-blue-500",
        docId: "",
        postId: "",
        uid: "",
        updatedAt: "",
    }
];
